---

- name: Create the UEFI Partition
  changed_when: false 
  community.general.parted:
    device: "{{ boot_efi_device_name }}"
    number: "{{ boot_efi_partition_num }}"
    flags: [ boot ]
    label: gpt
    name: EFI Boot Partition
    part_end: "{{ boot_efi_partition_end }}"
    state: present

- name: Format UEFI Boot Partition (FAT32)
  filesystem:
    dev: "{{ boot_efi_partition_name }}"
    fstype: vfat
    opts: -F32
    force: true
    state: present

- name: Create the LVM Partition (/root and /home)
  community.general.parted:
    device: "{{ root_device_name }}"
    number: "{{ root_partition_num }}"
    flags: [ lvm ]
    label: gpt
    name: Linux LVM Partition
    part_start: "{{ root_partition_start }}"
    part_end: "{{ root_partition_end }}"
    state: present
  when: (root_device_name == home_device_name) and (root_partition_num == home_partition_num)

- name: Create the root LVM Partition
  community.general.parted:
    device: "{{ root_device_name }}"
    number: "{{ root_partition_num }}"
    flags: [ lvm ]
    label: gpt
    name: Linux LVM root Partition
    part_start: "{{ root_partition_start }}"
    part_end: "{{ root_partition_end }}"
    state: present
  when: (root_device_name != home_device_name) or (root_partition_num != home_partition_num)

- name: Create the home LVM Partition
  community.general.parted:
    device: "{{ home_device_name }}"
    number: "{{ home_partition_num }}"
    flags: [ lvm ]
    label: gpt
    name: Linux LVM home Partition
    part_start: "{{ home_partition_start }}"
    part_end: "{{ home_partition_end }}"
    state: present
  when: (root_device_name != home_device_name) or (root_partition_num != home_partition_num)

- name: Install lvm2 dependency
  package:
    name: lvm2
    state: present
    update_cache: true

- name: Create the Volume Group(s)
  community.general.lvg:
    vg: "{{ item.name }}"
    pvs: "{{ item.pvs }}"
    pesize: 16
    pvresize: true
  loop: "{{ volume_groups }}"

- name: Create Logical Volume for /root
  community.general.lvol:
    vg: "{{ root_lvm_group_name }}"
    lv: root_lv
    size: "{{ root_lv_size }}"
    shrink: false

- name: Create Logical Volume for /home
  community.general.lvol:
    vg: "{{ home_lvm_group_name }}"
    lv: home_lv
    size: "{{ home_lv_size }}"
    shrink: false

- name: Format root LVM Partition (ext4)
  filesystem:
    dev: "/dev/{{ root_lvm_group_name }}/root_lv"
    fstype: ext4
    state: present

- name: Format home LVM Partition (ext4)
  filesystem:
    dev: "/dev/{{ home_lvm_group_name }}/home_lv"
    fstype: ext4
    state: present

- name: Mount the root device
  mount:
    path: /mnt
    src: "/dev/{{ root_lvm_group_name }}/root_lv"
    fstype: ext4
    opts: rw,relatime
    passno: 1
    state: mounted

- name: Create the /mnt/home folder
  file:
    path: /mnt/home
    state: directory

- name: Mount the home device
  mount:
    path: /mnt/home
    src: "/dev/{{ home_lvm_group_name }}/home_lv"
    fstype: ext4
    opts: rw,relatime
    passno: 2
    state: mounted
  notify: gen_fstab
