---

- name: Prepare the installation - disk partitions & pacstrap
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml

  roles:
    - disk

  tasks:
  - name: Pacstrap
    command:
      cmd: pacstrap /mnt base
      creates: /mnt/usr
