---

- name: Initial Setup (base packages and kernel creation) from a chroot environment
  hosts: localhost
  connection: local
  vars_files:
    - ~/.ansible/vaults/arch_linux_setup

  tasks:
    - name: Install needed base packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - linux
        - linux-headers
        - linux-lts
        - linux-lts-headers
        - neovim
        - base-devel
        - openssh
        - networkmanager
        - wpa_supplicant
        - wireless_tools
        - netctl
        - dialog
        - lvm2
        - sudo

    - name: Enable sshd and NetworkManager services
      service:
        name: "{{ item }}"
        enabled: true
      loop:
        - sshd
        - NetworkManager

    - name: Update mkinitcpio config
      lineinfile:
        path: /etc/mkinitcpio.conf
        regexp: "^#\\s+HOOKS=\\(base udev modconf block lvm2 filesystems fsck\\)"
        line: "HOOKS=(base udev modconf block lvm2 filesystems fsck)"
        state: present

    - name: Update locale.gen config
      lineinfile:
        path: /etc/locale.gen
        regexp: "^#en_US.UTF-8 UTF-8"
        line: "en_US.UTF-8 UTF-8"
        state: present
        notify: exec_locale_gen

    - name: Create the main user
      user:
        name: "{{ main_user_name }}"
        group: "{{ main_user_group }}"
        groups: wheel
        password: "{{ main_user_pwd | password_hash('sha512', main_user_salt) }}"
        state: present

    - name: Set the wheel group in the sudoers file to nopasswd
      lineinfile:
        path: /etc/sudoers
        regexp: "^# %wheel ALL=\\(ALL:ALL\\) NOPASSWD: ALL"
        line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
        state: present

  handlers:
    - name: exec_locale_gen
      command:
        cmd: locale-gen

