---

- name: Bootstrapping a new Arch Linux workstation
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    community.general.pacman:
      name:
        - tmux
        - bat
        - bc
        - htop
        - alacritty
        - chromium
        - clang
        - cmake
        - curl
        - wget
        - darktable
        - feh
        - freetype2
        - fzf
        - gcc
        - gimp
        - gnome-calculator
        - gnupg
        - graphviz
        - gzip
        - i3-wm
        - i3blocks
        - i3status
        - keepassxc
        - lazygit
        - lua
        - make
        - neovim
        - picom
        - ranger
        - ripgrep
        - rofi
        - sed
        - stow
        - task
        - tree
        - tree-sitter
        - ttf-font-awesome
        - unzip
        - vulkan-headers
        - vulkan-icd-loader
        - vulkan-tools
        - vulkan-validation-layers
        - vulkan-validation-layers
        - zsh
      state: present
  
  - name: dotfiles git clone
    become_user: jcpennel
    register: dotfiles_status
    git:
      repo: https://github.com/shiffu/dotfiles.git
      dest: $HOME/dotfiles

  - name: Stow dotfiles
    become_user: jcpennel
    stow:
      state: present
      package: '{{ item }}'
      dir: $HOME/dotfiles
    with_items:
      - git
      - mergetool
      - zsh
      - tmux
      - nvim
      - alacritty
      - task
      - gdb
      - i3
      - i3blocks

  - name: Activate zsh as default Shell
    shell:
      cmd: chsh -s /usr/bin/zsh jcpennel
    when: ansible_facts['user_shell'] != '/usr/bin/zsh'
