---

- name: Setting up a new Arch Linux workstation
  hosts: localhost
  connection: local

  roles:
    - base

- name: Setting up KDE specific config
  hosts: localhost
  connection: local

  roles:
    - kde
