---

- name: Creates the ansible group and user with ssh key and sudoers config
  hosts: initial_setup
  remote_user: root
  vars_files:
    - ~/.ansible/vaults/arch_linux_setup
  vars:
    ssh_key_id: ./ssh_keys/ansible_id_rsa
    ansible_ssh_pass: "{{ root_pwd }}"

  tasks:
    - name: Create the ssh key pair
      connection: local
      openssh_keypair:
        path: "{{ ssh_key_id }}"
        type: rsa
        state: present

    - name: Create the ansible group
      group:
        name: "{{ ansible_user_group }}"
        state: present
      
    - name: Create the ansible user
      user:
        name: "{{ ansible_user_name }}"
        group: "{{ ansible_user_group }}"
        groups: wheel
        password: "{{ ansible_user_pwd | password_hash('sha512', ansible_user_salt) }}"
        state: present

    - name: Ensure the ~/.ssh directory of the 'ansible' user exists
      file:
        path: "~{{ ansible_user_name }}/.ssh"
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_group }}"
        mode: 0700
        state: directory

    - name: Copy newly created ssh pub key in the authorized_keys file
      copy:
        src: "{{ ssh_key_id }}.pub"
        dest: "~{{ ansible_user_name }}/.ssh/authorized_keys"
        owner: "{{ ansible_user_name }}"
        group: "{{ ansible_user_group }}"
        mode: 0600

    - name: Set the wheel group in the sudoers file to nopasswd
      lineinfile:
        path: /etc/sudoers
        regexp: "^# %wheel ALL=\\(ALL:ALL\\) NOPASSWD: ALL"
        line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
        state: present
      notify: restart_sshd

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
