---

- name: Update pacman cache
  pacman:
    update_cache: yes

- name: Install packages
  package:
    name:
      - man
      - tmux
      - bat
      - bc
      - bind
      - btop
      - htop
      - alacritty
      - arandr
      - bluez
      - bluez-utils
      - chromium
      - clang
      - cloc
      - cmake
      - cmatrix
      - darktable
      - fzf
      - gcc
      - gdb
      - gimp
      - gnome-calculator
      - gnupg
      - graphviz
      - gzip
      - keepassxc
      - lazygit
      - lf
      - linux-firmware
      - lua
      - make
      - neofetch
      - neovim
      - nvidia
      - nvidia-lts
      - openssh
      - pamixer
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - remmina
      - ripgrep
      - sed
      - stow
      - task
      - taskwarrior-tui
      - tigervnc
      - tree
      - tree-sitter
      - ttf-font-awesome
      - ttf-hack-nerd
      - unzip
      - usbutils
      - vulkan-headers
      - vulkan-icd-loader
      - vulkan-tools
      - vulkan-validation-layers
      - vulkan-validation-layers
      - xorg-xauth
      - xorg-xrandr
      - zsh
    state: present

- name: dotfiles git clone
  become_user: '{{ user_name }}'
  git:
    repo: https://github.com/shiffu/dotfiles.git
    dest: '/home/{{ user_name }}/dotfiles'

- name: Stow dotfiles
  become_user: '{{ user_name }}'
  stow:
    state: present
    package: '{{ item }}'
    dir: '/home/{{ user_name }}/dotfiles'
  loop:
    - alacritty
    - git
    - lazygit
    # - mergetool # This goes with p4merge tool
    - zsh
    - rofi
    - tmux
    - nvim
    - task
    - gdb

- name: Check user's Shell
  shell:
    cmd: "cat /etc/passwd | grep {{ user_name }} | cut -d: -f7"
  register: user_shell
  changed_when: false

- name: Activate zsh as default Shell
  shell:
    cmd: 'chsh -s /usr/bin/zsh {{ user_name }}'
  when: user_shell.stdout != "/usr/bin/zsh"

- name: Create the SynologyDrive Root folder
  file:
    owner: "{{ user_name }}"
    path: /home/{{ user_name }}/SynologyDrive
    state: directory

- name: Create the SynologyDrive subfolders
  file:
    owner: "{{ user_name }}"
    path: /home/{{ user_name }}/SynologyDrive/{{ item }}
    state: directory
  loop:
    - dev
    - keepass
    - taskwarrior
    - wallpapers

- name: Prepare default symlinks to SynologyDrive main folders
  file:
    path: /home/{{ user_name }}/{{ item.link }}
    src: /home/{{ user_name }}/SynologyDrive/{{ item.src }}
    state: link
  loop:
    - { link: .task, src: taskwarrior }
    - { link: wallpapers, src: wallpapers }

- name: Set the proper timezone
  timezone:
    name: "US/Eastern"
  notify: timezone_update

# - name: Extract P4Merge tgz
#   unarchive:
#     owner: '{{ user_name }}'
#     remote_src: true
#     src: '{{ p4merge_tgz_uri }}'
#     dest: /opt
#     creates: '/opt/{{ p4merge_dir }}/'
#
# - name: Add symlink to p4merge binary in /usr/bin
#   shell: 'ln -s /opt/{{ p4merge_dir }}/bin/p4merge p4merge'
#   args:
#     chdir: /usr/bin/
#     creates: p4merge
