---

- name: Install i3 'dependencies'
  package:
    name:
      - dunst
      - libnotify
      - feh
      - lightdm
      - lightdm-gtk-greeter
      - picom
      - xclip
      - xorg-server
    state: present

- name: Install i3 specific packages
  register: i3_install_status
  package:
    name:
      - i3-wm
      - polybar
    state: present

- name: Check if default i3 config is installed
  stat:
    path: /home/{{ user_name }}/.config/i3
  register: i3_config

- name: Delete default i3 config if it exists
  file:
    path: /home/{{ user_name }}/.config/i3
    state: absent
  when: i3_config.stat.isdir is defined and i3_config.stat.isdir == true

- name: Stow dotfiles
  become_user: '{{ user_name }}'
  # when: i3_install_status.changed == true
  stow:
    state: present
    package: '{{ item }}'
    dir: "/home/{{ user_name }}/dotfiles/"
  loop:
    - dunst
    - i3
    - polybar
    - picom
    - scripts

- name: LightDM service Enable
  service:
    name: lightdm
    state: started
    enabled: yes
