---

- name: Install grub packages
  package:
    state: present
    name:
      - grub
      - efibootmgr
      - dosfstools
      - os-prober
      - mtools

- name: Create the EFI folder
  file:
    path: /boot/EFI
    state: directory

- name: Mount the EFI folder
  mount:
    path: /boot/EFI/
    src: "{{ install_device_name }}1"
    opts: rw,relatime
    fstype: vfat
    state: mounted

- name: Run grub-install
  command:
    cmd: grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck

- name: Check /boot/grub/locale exists
  file:
    path: /boot/grub/locale/
    state: directory

- name: Copy locale file
  copy:
    remote_src: true
    src: /usr/share/locale/en@quot/LC_MESSAGES/grub.mo
    dest: /boot/grub/locale/en.mo

- name: Run grub-mkconfig
  command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg

